/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.docservice.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Document extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4988508939589171101L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Document\",\"namespace\":\"com.example.docservice.schema\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"companyId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"bankDetails\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Document> ENCODER =
      new BinaryMessageEncoder<Document>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Document> DECODER =
      new BinaryMessageDecoder<Document>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Document> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Document> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Document> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Document>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Document to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Document from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Document instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Document fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence id;
  private java.lang.CharSequence companyId;
  private java.lang.CharSequence bankDetails;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Document() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param companyId The new value for companyId
   * @param bankDetails The new value for bankDetails
   */
  public Document(java.lang.CharSequence id, java.lang.CharSequence companyId, java.lang.CharSequence bankDetails) {
    this.id = id;
    this.companyId = companyId;
    this.bankDetails = bankDetails;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return companyId;
    case 2: return bankDetails;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: companyId = (java.lang.CharSequence)value$; break;
    case 2: bankDetails = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'companyId' field.
   * @return The value of the 'companyId' field.
   */
  public java.lang.CharSequence getCompanyId() {
    return companyId;
  }


  /**
   * Sets the value of the 'companyId' field.
   * @param value the value to set.
   */
  public void setCompanyId(java.lang.CharSequence value) {
    this.companyId = value;
  }

  /**
   * Gets the value of the 'bankDetails' field.
   * @return The value of the 'bankDetails' field.
   */
  public java.lang.CharSequence getBankDetails() {
    return bankDetails;
  }


  /**
   * Sets the value of the 'bankDetails' field.
   * @param value the value to set.
   */
  public void setBankDetails(java.lang.CharSequence value) {
    this.bankDetails = value;
  }

  /**
   * Creates a new Document RecordBuilder.
   * @return A new Document RecordBuilder
   */
  public static com.example.docservice.schema.Document.Builder newBuilder() {
    return new com.example.docservice.schema.Document.Builder();
  }

  /**
   * Creates a new Document RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Document RecordBuilder
   */
  public static com.example.docservice.schema.Document.Builder newBuilder(com.example.docservice.schema.Document.Builder other) {
    if (other == null) {
      return new com.example.docservice.schema.Document.Builder();
    } else {
      return new com.example.docservice.schema.Document.Builder(other);
    }
  }

  /**
   * Creates a new Document RecordBuilder by copying an existing Document instance.
   * @param other The existing instance to copy.
   * @return A new Document RecordBuilder
   */
  public static com.example.docservice.schema.Document.Builder newBuilder(com.example.docservice.schema.Document other) {
    if (other == null) {
      return new com.example.docservice.schema.Document.Builder();
    } else {
      return new com.example.docservice.schema.Document.Builder(other);
    }
  }

  /**
   * RecordBuilder for Document instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Document>
    implements org.apache.avro.data.RecordBuilder<Document> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence companyId;
    private java.lang.CharSequence bankDetails;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.docservice.schema.Document.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.companyId)) {
        this.companyId = data().deepCopy(fields()[1].schema(), other.companyId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.bankDetails)) {
        this.bankDetails = data().deepCopy(fields()[2].schema(), other.bankDetails);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Document instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.docservice.schema.Document other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.companyId)) {
        this.companyId = data().deepCopy(fields()[1].schema(), other.companyId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bankDetails)) {
        this.bankDetails = data().deepCopy(fields()[2].schema(), other.bankDetails);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.example.docservice.schema.Document.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.example.docservice.schema.Document.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'companyId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCompanyId() {
      return companyId;
    }


    /**
      * Sets the value of the 'companyId' field.
      * @param value The value of 'companyId'.
      * @return This builder.
      */
    public com.example.docservice.schema.Document.Builder setCompanyId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.companyId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'companyId' field has been set.
      * @return True if the 'companyId' field has been set, false otherwise.
      */
    public boolean hasCompanyId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'companyId' field.
      * @return This builder.
      */
    public com.example.docservice.schema.Document.Builder clearCompanyId() {
      companyId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'bankDetails' field.
      * @return The value.
      */
    public java.lang.CharSequence getBankDetails() {
      return bankDetails;
    }


    /**
      * Sets the value of the 'bankDetails' field.
      * @param value The value of 'bankDetails'.
      * @return This builder.
      */
    public com.example.docservice.schema.Document.Builder setBankDetails(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.bankDetails = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'bankDetails' field has been set.
      * @return True if the 'bankDetails' field has been set, false otherwise.
      */
    public boolean hasBankDetails() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'bankDetails' field.
      * @return This builder.
      */
    public com.example.docservice.schema.Document.Builder clearBankDetails() {
      bankDetails = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Document build() {
      try {
        Document record = new Document();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.companyId = fieldSetFlags()[1] ? this.companyId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.bankDetails = fieldSetFlags()[2] ? this.bankDetails : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Document>
    WRITER$ = (org.apache.avro.io.DatumWriter<Document>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Document>
    READER$ = (org.apache.avro.io.DatumReader<Document>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.id);
    }

    if (this.companyId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.companyId);
    }

    if (this.bankDetails == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.bankDetails);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.id = null;
      } else {
        this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.companyId = null;
      } else {
        this.companyId = in.readString(this.companyId instanceof Utf8 ? (Utf8)this.companyId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.bankDetails = null;
      } else {
        this.bankDetails = in.readString(this.bankDetails instanceof Utf8 ? (Utf8)this.bankDetails : null);
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id = null;
          } else {
            this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.companyId = null;
          } else {
            this.companyId = in.readString(this.companyId instanceof Utf8 ? (Utf8)this.companyId : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.bankDetails = null;
          } else {
            this.bankDetails = in.readString(this.bankDetails instanceof Utf8 ? (Utf8)this.bankDetails : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










