/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.docservice.schema;
@org.apache.avro.specific.AvroGenerated
public enum FormOwnership implements org.apache.avro.generic.GenericEnumSymbol<FormOwnership> {
  INDIVIDUAL_ENTREPRENEUR, UNITARY_ENTERPRISE, LLC  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FormOwnership\",\"namespace\":\"com.example.docservice.schema\",\"symbols\":[\"INDIVIDUAL_ENTREPRENEUR\",\"UNITARY_ENTERPRISE\",\"LLC\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
